"""Run the three checks. Do not edit this file."""
import sys

import area
import slug
import quarter

CASES = [
    ("area.rect", lambda: area.rect(3, 4), 12),
    ("slug.make", lambda: slug.make("Hello  World"), "hello-world"),
    ("quarter.of", lambda: quarter.of(11), 4),
]


def main():
    failed = 0
    for name, call, want in CASES:
        got = call()
        if got == want:
            print(f"pass {name}")
        else:
            print(f"FAIL {name}: got {got!r}, want {want!r}")
            failed += 1
    print("\nALL OK" if not failed else f"\n{failed} check(s) failing")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
