// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsRequestPoint } from "./AnalyticsRequestPoint";

export type ThreadAnalytics = { threadId: string,
/**
 * From the sidecar header; `None` when the header line was unreadable.
 */
model: string | null, provider: string | null, startedAt: string | null, lastTimestamp: string | null, requests: bigint, invisibleRequests: bigint, inputTokens: bigint, cachedInputTokens: bigint, outputTokens: bigint, reasoningOutputTokens: bigint, timeline: Array<AnalyticsRequestPoint>,
/**
 * True when the timeline was capped; the token sums above still cover
 * every request in the file.
 */
timelineTruncated: boolean, };
