"""Run every check and report which ones fail. Do not edit this file."""
import sys

import dates
import numbers_util
import shapes
import strings

CASES = [
    ("shapes.rect_area", lambda: shapes.rect_area(3, 4), 12),
    ("shapes.circle_area", lambda: round(shapes.circle_area(2), 4), 12.5664),
    ("strings.slugify", lambda: strings.slugify("Hello  World Again"), "hello-world-again"),
    ("strings.truncate", lambda: strings.truncate("abcdefgh", 5), "ab..."),
    ("numbers_util.median", lambda: numbers_util.median([5, 1, 3, 2, 4]), 3),
    ("numbers_util.clamp", lambda: numbers_util.clamp(12, 0, 10), 10),
    ("dates.is_leap", lambda: dates.is_leap(1900), False),
    ("dates.quarter", lambda: dates.quarter(11), 4),
]


def main():
    failed = 0
    for name, call, want in CASES:
        try:
            got = call()
        except Exception as exc:  # noqa: BLE001
            print(f"FAIL {name}: raised {exc!r}")
            failed += 1
            continue
        if got != want:
            print(f"FAIL {name}: got {got!r}, want {want!r}")
            failed += 1
        else:
            print(f"pass {name}")
    if failed:
        print(f"\n{failed} check(s) failing")
        return 1
    print("\nALL OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
